const {
	ENVIRONMENT,
	PORT,
	HOST,
	KNEX_CLIENT,
	KNEX_FILENAME,
	KNEX_HOST,
	KNEX_PORT,
	KNEX_USER,
	KNEX_DATABASE,
	KNEX_PASSWORD,
	FIREBASE_CONFIG,
	FIREBASE_DEFAULT_USER_ID,
	FIREBASE_DEFAULT_USER_TOKEN,
	FIREBASE_TOKEN_VERIFICATION,

} = process.env;

export {
	ENVIRONMENT,
	PORT,
	HOST,
	KNEX_CLIENT,
	KNEX_FILENAME,
	KNEX_HOST,
	KNEX_PORT,
	KNEX_USER,
	KNEX_DATABASE,
	KNEX_PASSWORD,
	FIREBASE_CONFIG,
	FIREBASE_DEFAULT_USER_ID,
	FIREBASE_DEFAULT_USER_TOKEN,
	FIREBASE_TOKEN_VERIFICATION,
};
